server:
  port: 20001

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: api-server

eureka:
  instance:
    # 每隔10s发送一次心跳
    lease-renewal-interval-in-seconds: 10
    # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/

feign:
  hystrix:
    enabled: true