spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: api-server
  # Redis
  redis:
    host: 127.0.0.1
    #password: 123456
    # 数据库索引 默认0
    database: 0
    port: 9637
    timeout: 3000
    password: 69F0ef5dd1d62ab48b13834286403A
server:
  port: 2008
eureka:
  instance:
    # 每隔10s发送一次心跳
    lease-renewal-interval-in-seconds: 10
    # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/