spring:
  application:
    name: zuul-server
server:
  port: 4001
eureka:
  instance:
    # 每隔10s发送一次心跳
    lease-renewal-interval-in-seconds: 10
    # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
#如果不配置，默认会把eureka里注册的服务，按服务名字匹配url路径
#下面是为了自定义一个到order-server的url路径
zuul:
  routes:
    api-a:
      path: /custom-order-url/**
      serviceId: order-server
    admin:
      path: /admin/**
      serviceId: admin-server