spring:
  application:
    name: zuul-server
server:
  port: 4001
eureka:
  instance:
    # 每隔10s发送一次心跳
    lease-renewal-interval-in-seconds: 10
    # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: order-server